services:
  presentation:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    container_name: asciidoc-revealjs-presentation
    ports:
      - "4200:4200"
    volumes:
      - ../../docs:/app/docs
    environment:
      - PORT=4200
    restart: unless-stopped
